//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetrisClient.Web.TetrisWebService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://M32COM-Tetris.org/", ConfigurationName="TetrisWebService.TetrisWebServiceSoap")]
    public interface TetrisWebServiceSoap {
        
        // CODEGEN: Parameter 'StartGameResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://M32COM-Tetris.org/StartGame", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TetrisClient.Web.TetrisWebService.StartGameResponse StartGame(TetrisClient.Web.TetrisWebService.StartGameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://M32COM-Tetris.org/StartGame", ReplyAction="*")]
        System.Threading.Tasks.Task<TetrisClient.Web.TetrisWebService.StartGameResponse> StartGameAsync(TetrisClient.Web.TetrisWebService.StartGameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://M32COM-Tetris.org/GetGameState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool GetGameState();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://M32COM-Tetris.org/GetGameState", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> GetGameStateAsync();
        
        // CODEGEN: Parameter 'GetBoardResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://M32COM-Tetris.org/GetBoard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TetrisClient.Web.TetrisWebService.GetBoardResponse GetBoard(TetrisClient.Web.TetrisWebService.GetBoardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://M32COM-Tetris.org/GetBoard", ReplyAction="*")]
        System.Threading.Tasks.Task<TetrisClient.Web.TetrisWebService.GetBoardResponse> GetBoardAsync(TetrisClient.Web.TetrisWebService.GetBoardRequest request);
        
        // CODEGEN: Parameter 'GetNextShapeResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://M32COM-Tetris.org/GetNextShape", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TetrisClient.Web.TetrisWebService.GetNextShapeResponse GetNextShape(TetrisClient.Web.TetrisWebService.GetNextShapeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://M32COM-Tetris.org/GetNextShape", ReplyAction="*")]
        System.Threading.Tasks.Task<TetrisClient.Web.TetrisWebService.GetNextShapeResponse> GetNextShapeAsync(TetrisClient.Web.TetrisWebService.GetNextShapeRequest request);
        
        // CODEGEN: Parameter 'MoveBlockLeftResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://M32COM-Tetris.org/MoveBlockLeft", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TetrisClient.Web.TetrisWebService.MoveBlockLeftResponse MoveBlockLeft(TetrisClient.Web.TetrisWebService.MoveBlockLeftRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://M32COM-Tetris.org/MoveBlockLeft", ReplyAction="*")]
        System.Threading.Tasks.Task<TetrisClient.Web.TetrisWebService.MoveBlockLeftResponse> MoveBlockLeftAsync(TetrisClient.Web.TetrisWebService.MoveBlockLeftRequest request);
        
        // CODEGEN: Parameter 'MoveBlockRightResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://M32COM-Tetris.org/MoveBlockRight", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TetrisClient.Web.TetrisWebService.MoveBlockRightResponse MoveBlockRight(TetrisClient.Web.TetrisWebService.MoveBlockRightRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://M32COM-Tetris.org/MoveBlockRight", ReplyAction="*")]
        System.Threading.Tasks.Task<TetrisClient.Web.TetrisWebService.MoveBlockRightResponse> MoveBlockRightAsync(TetrisClient.Web.TetrisWebService.MoveBlockRightRequest request);
        
        // CODEGEN: Parameter 'RotateBlockResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://M32COM-Tetris.org/RotateBlock", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TetrisClient.Web.TetrisWebService.RotateBlockResponse RotateBlock(TetrisClient.Web.TetrisWebService.RotateBlockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://M32COM-Tetris.org/RotateBlock", ReplyAction="*")]
        System.Threading.Tasks.Task<TetrisClient.Web.TetrisWebService.RotateBlockResponse> RotateBlockAsync(TetrisClient.Web.TetrisWebService.RotateBlockRequest request);
        
        // CODEGEN: Parameter 'MoveBlockDownResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://M32COM-Tetris.org/MoveBlockDown", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TetrisClient.Web.TetrisWebService.MoveBlockDownResponse MoveBlockDown(TetrisClient.Web.TetrisWebService.MoveBlockDownRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://M32COM-Tetris.org/MoveBlockDown", ReplyAction="*")]
        System.Threading.Tasks.Task<TetrisClient.Web.TetrisWebService.MoveBlockDownResponse> MoveBlockDownAsync(TetrisClient.Web.TetrisWebService.MoveBlockDownRequest request);
        
        // CODEGEN: Parameter 'DropBlockResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://M32COM-Tetris.org/DropBlock", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TetrisClient.Web.TetrisWebService.DropBlockResponse DropBlock(TetrisClient.Web.TetrisWebService.DropBlockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://M32COM-Tetris.org/DropBlock", ReplyAction="*")]
        System.Threading.Tasks.Task<TetrisClient.Web.TetrisWebService.DropBlockResponse> DropBlockAsync(TetrisClient.Web.TetrisWebService.DropBlockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://M32COM-Tetris.org/GetScore", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetScore();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://M32COM-Tetris.org/GetScore", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetScoreAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://M32COM-Tetris.org/GetHighScores", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetHighScores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://M32COM-Tetris.org/GetHighScores", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetHighScoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://M32COM-Tetris.org/SubmitScore", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SubmitScore();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://M32COM-Tetris.org/SubmitScore", ReplyAction="*")]
        System.Threading.Tasks.Task SubmitScoreAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://M32COM-Tetris.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://M32COM-Tetris.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StartGame", WrapperNamespace="http://M32COM-Tetris.org/", IsWrapped=true)]
    public partial class StartGameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://M32COM-Tetris.org/", Order=0)]
        public string player;
        
        public StartGameRequest() {
        }
        
        public StartGameRequest(string player) {
            this.player = player;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StartGameResponse", WrapperNamespace="http://M32COM-Tetris.org/", IsWrapped=true)]
    public partial class StartGameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://M32COM-Tetris.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] StartGameResult;
        
        public StartGameResponse() {
        }
        
        public StartGameResponse(string[][] StartGameResult) {
            this.StartGameResult = StartGameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBoard", WrapperNamespace="http://M32COM-Tetris.org/", IsWrapped=true)]
    public partial class GetBoardRequest {
        
        public GetBoardRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBoardResponse", WrapperNamespace="http://M32COM-Tetris.org/", IsWrapped=true)]
    public partial class GetBoardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://M32COM-Tetris.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetBoardResult;
        
        public GetBoardResponse() {
        }
        
        public GetBoardResponse(string[][] GetBoardResult) {
            this.GetBoardResult = GetBoardResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNextShape", WrapperNamespace="http://M32COM-Tetris.org/", IsWrapped=true)]
    public partial class GetNextShapeRequest {
        
        public GetNextShapeRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNextShapeResponse", WrapperNamespace="http://M32COM-Tetris.org/", IsWrapped=true)]
    public partial class GetNextShapeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://M32COM-Tetris.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetNextShapeResult;
        
        public GetNextShapeResponse() {
        }
        
        public GetNextShapeResponse(string[][] GetNextShapeResult) {
            this.GetNextShapeResult = GetNextShapeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MoveBlockLeft", WrapperNamespace="http://M32COM-Tetris.org/", IsWrapped=true)]
    public partial class MoveBlockLeftRequest {
        
        public MoveBlockLeftRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MoveBlockLeftResponse", WrapperNamespace="http://M32COM-Tetris.org/", IsWrapped=true)]
    public partial class MoveBlockLeftResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://M32COM-Tetris.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] MoveBlockLeftResult;
        
        public MoveBlockLeftResponse() {
        }
        
        public MoveBlockLeftResponse(string[][] MoveBlockLeftResult) {
            this.MoveBlockLeftResult = MoveBlockLeftResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MoveBlockRight", WrapperNamespace="http://M32COM-Tetris.org/", IsWrapped=true)]
    public partial class MoveBlockRightRequest {
        
        public MoveBlockRightRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MoveBlockRightResponse", WrapperNamespace="http://M32COM-Tetris.org/", IsWrapped=true)]
    public partial class MoveBlockRightResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://M32COM-Tetris.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] MoveBlockRightResult;
        
        public MoveBlockRightResponse() {
        }
        
        public MoveBlockRightResponse(string[][] MoveBlockRightResult) {
            this.MoveBlockRightResult = MoveBlockRightResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RotateBlock", WrapperNamespace="http://M32COM-Tetris.org/", IsWrapped=true)]
    public partial class RotateBlockRequest {
        
        public RotateBlockRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RotateBlockResponse", WrapperNamespace="http://M32COM-Tetris.org/", IsWrapped=true)]
    public partial class RotateBlockResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://M32COM-Tetris.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] RotateBlockResult;
        
        public RotateBlockResponse() {
        }
        
        public RotateBlockResponse(string[][] RotateBlockResult) {
            this.RotateBlockResult = RotateBlockResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MoveBlockDown", WrapperNamespace="http://M32COM-Tetris.org/", IsWrapped=true)]
    public partial class MoveBlockDownRequest {
        
        public MoveBlockDownRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MoveBlockDownResponse", WrapperNamespace="http://M32COM-Tetris.org/", IsWrapped=true)]
    public partial class MoveBlockDownResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://M32COM-Tetris.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] MoveBlockDownResult;
        
        public MoveBlockDownResponse() {
        }
        
        public MoveBlockDownResponse(string[][] MoveBlockDownResult) {
            this.MoveBlockDownResult = MoveBlockDownResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DropBlock", WrapperNamespace="http://M32COM-Tetris.org/", IsWrapped=true)]
    public partial class DropBlockRequest {
        
        public DropBlockRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DropBlockResponse", WrapperNamespace="http://M32COM-Tetris.org/", IsWrapped=true)]
    public partial class DropBlockResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://M32COM-Tetris.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] DropBlockResult;
        
        public DropBlockResponse() {
        }
        
        public DropBlockResponse(string[][] DropBlockResult) {
            this.DropBlockResult = DropBlockResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TetrisWebServiceSoapChannel : TetrisClient.Web.TetrisWebService.TetrisWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TetrisWebServiceSoapClient : System.ServiceModel.ClientBase<TetrisClient.Web.TetrisWebService.TetrisWebServiceSoap>, TetrisClient.Web.TetrisWebService.TetrisWebServiceSoap {
        
        public TetrisWebServiceSoapClient() {
        }
        
        public TetrisWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TetrisWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TetrisWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TetrisWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TetrisClient.Web.TetrisWebService.StartGameResponse TetrisClient.Web.TetrisWebService.TetrisWebServiceSoap.StartGame(TetrisClient.Web.TetrisWebService.StartGameRequest request) {
            return base.Channel.StartGame(request);
        }
        
        public string[][] StartGame(string player) {
            TetrisClient.Web.TetrisWebService.StartGameRequest inValue = new TetrisClient.Web.TetrisWebService.StartGameRequest();
            inValue.player = player;
            TetrisClient.Web.TetrisWebService.StartGameResponse retVal = ((TetrisClient.Web.TetrisWebService.TetrisWebServiceSoap)(this)).StartGame(inValue);
            return retVal.StartGameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TetrisClient.Web.TetrisWebService.StartGameResponse> TetrisClient.Web.TetrisWebService.TetrisWebServiceSoap.StartGameAsync(TetrisClient.Web.TetrisWebService.StartGameRequest request) {
            return base.Channel.StartGameAsync(request);
        }
        
        public System.Threading.Tasks.Task<TetrisClient.Web.TetrisWebService.StartGameResponse> StartGameAsync(string player) {
            TetrisClient.Web.TetrisWebService.StartGameRequest inValue = new TetrisClient.Web.TetrisWebService.StartGameRequest();
            inValue.player = player;
            return ((TetrisClient.Web.TetrisWebService.TetrisWebServiceSoap)(this)).StartGameAsync(inValue);
        }
        
        public bool GetGameState() {
            return base.Channel.GetGameState();
        }
        
        public System.Threading.Tasks.Task<bool> GetGameStateAsync() {
            return base.Channel.GetGameStateAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TetrisClient.Web.TetrisWebService.GetBoardResponse TetrisClient.Web.TetrisWebService.TetrisWebServiceSoap.GetBoard(TetrisClient.Web.TetrisWebService.GetBoardRequest request) {
            return base.Channel.GetBoard(request);
        }
        
        public string[][] GetBoard() {
            TetrisClient.Web.TetrisWebService.GetBoardRequest inValue = new TetrisClient.Web.TetrisWebService.GetBoardRequest();
            TetrisClient.Web.TetrisWebService.GetBoardResponse retVal = ((TetrisClient.Web.TetrisWebService.TetrisWebServiceSoap)(this)).GetBoard(inValue);
            return retVal.GetBoardResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TetrisClient.Web.TetrisWebService.GetBoardResponse> TetrisClient.Web.TetrisWebService.TetrisWebServiceSoap.GetBoardAsync(TetrisClient.Web.TetrisWebService.GetBoardRequest request) {
            return base.Channel.GetBoardAsync(request);
        }
        
        public System.Threading.Tasks.Task<TetrisClient.Web.TetrisWebService.GetBoardResponse> GetBoardAsync() {
            TetrisClient.Web.TetrisWebService.GetBoardRequest inValue = new TetrisClient.Web.TetrisWebService.GetBoardRequest();
            return ((TetrisClient.Web.TetrisWebService.TetrisWebServiceSoap)(this)).GetBoardAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TetrisClient.Web.TetrisWebService.GetNextShapeResponse TetrisClient.Web.TetrisWebService.TetrisWebServiceSoap.GetNextShape(TetrisClient.Web.TetrisWebService.GetNextShapeRequest request) {
            return base.Channel.GetNextShape(request);
        }
        
        public string[][] GetNextShape() {
            TetrisClient.Web.TetrisWebService.GetNextShapeRequest inValue = new TetrisClient.Web.TetrisWebService.GetNextShapeRequest();
            TetrisClient.Web.TetrisWebService.GetNextShapeResponse retVal = ((TetrisClient.Web.TetrisWebService.TetrisWebServiceSoap)(this)).GetNextShape(inValue);
            return retVal.GetNextShapeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TetrisClient.Web.TetrisWebService.GetNextShapeResponse> TetrisClient.Web.TetrisWebService.TetrisWebServiceSoap.GetNextShapeAsync(TetrisClient.Web.TetrisWebService.GetNextShapeRequest request) {
            return base.Channel.GetNextShapeAsync(request);
        }
        
        public System.Threading.Tasks.Task<TetrisClient.Web.TetrisWebService.GetNextShapeResponse> GetNextShapeAsync() {
            TetrisClient.Web.TetrisWebService.GetNextShapeRequest inValue = new TetrisClient.Web.TetrisWebService.GetNextShapeRequest();
            return ((TetrisClient.Web.TetrisWebService.TetrisWebServiceSoap)(this)).GetNextShapeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TetrisClient.Web.TetrisWebService.MoveBlockLeftResponse TetrisClient.Web.TetrisWebService.TetrisWebServiceSoap.MoveBlockLeft(TetrisClient.Web.TetrisWebService.MoveBlockLeftRequest request) {
            return base.Channel.MoveBlockLeft(request);
        }
        
        public string[][] MoveBlockLeft() {
            TetrisClient.Web.TetrisWebService.MoveBlockLeftRequest inValue = new TetrisClient.Web.TetrisWebService.MoveBlockLeftRequest();
            TetrisClient.Web.TetrisWebService.MoveBlockLeftResponse retVal = ((TetrisClient.Web.TetrisWebService.TetrisWebServiceSoap)(this)).MoveBlockLeft(inValue);
            return retVal.MoveBlockLeftResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TetrisClient.Web.TetrisWebService.MoveBlockLeftResponse> TetrisClient.Web.TetrisWebService.TetrisWebServiceSoap.MoveBlockLeftAsync(TetrisClient.Web.TetrisWebService.MoveBlockLeftRequest request) {
            return base.Channel.MoveBlockLeftAsync(request);
        }
        
        public System.Threading.Tasks.Task<TetrisClient.Web.TetrisWebService.MoveBlockLeftResponse> MoveBlockLeftAsync() {
            TetrisClient.Web.TetrisWebService.MoveBlockLeftRequest inValue = new TetrisClient.Web.TetrisWebService.MoveBlockLeftRequest();
            return ((TetrisClient.Web.TetrisWebService.TetrisWebServiceSoap)(this)).MoveBlockLeftAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TetrisClient.Web.TetrisWebService.MoveBlockRightResponse TetrisClient.Web.TetrisWebService.TetrisWebServiceSoap.MoveBlockRight(TetrisClient.Web.TetrisWebService.MoveBlockRightRequest request) {
            return base.Channel.MoveBlockRight(request);
        }
        
        public string[][] MoveBlockRight() {
            TetrisClient.Web.TetrisWebService.MoveBlockRightRequest inValue = new TetrisClient.Web.TetrisWebService.MoveBlockRightRequest();
            TetrisClient.Web.TetrisWebService.MoveBlockRightResponse retVal = ((TetrisClient.Web.TetrisWebService.TetrisWebServiceSoap)(this)).MoveBlockRight(inValue);
            return retVal.MoveBlockRightResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TetrisClient.Web.TetrisWebService.MoveBlockRightResponse> TetrisClient.Web.TetrisWebService.TetrisWebServiceSoap.MoveBlockRightAsync(TetrisClient.Web.TetrisWebService.MoveBlockRightRequest request) {
            return base.Channel.MoveBlockRightAsync(request);
        }
        
        public System.Threading.Tasks.Task<TetrisClient.Web.TetrisWebService.MoveBlockRightResponse> MoveBlockRightAsync() {
            TetrisClient.Web.TetrisWebService.MoveBlockRightRequest inValue = new TetrisClient.Web.TetrisWebService.MoveBlockRightRequest();
            return ((TetrisClient.Web.TetrisWebService.TetrisWebServiceSoap)(this)).MoveBlockRightAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TetrisClient.Web.TetrisWebService.RotateBlockResponse TetrisClient.Web.TetrisWebService.TetrisWebServiceSoap.RotateBlock(TetrisClient.Web.TetrisWebService.RotateBlockRequest request) {
            return base.Channel.RotateBlock(request);
        }
        
        public string[][] RotateBlock() {
            TetrisClient.Web.TetrisWebService.RotateBlockRequest inValue = new TetrisClient.Web.TetrisWebService.RotateBlockRequest();
            TetrisClient.Web.TetrisWebService.RotateBlockResponse retVal = ((TetrisClient.Web.TetrisWebService.TetrisWebServiceSoap)(this)).RotateBlock(inValue);
            return retVal.RotateBlockResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TetrisClient.Web.TetrisWebService.RotateBlockResponse> TetrisClient.Web.TetrisWebService.TetrisWebServiceSoap.RotateBlockAsync(TetrisClient.Web.TetrisWebService.RotateBlockRequest request) {
            return base.Channel.RotateBlockAsync(request);
        }
        
        public System.Threading.Tasks.Task<TetrisClient.Web.TetrisWebService.RotateBlockResponse> RotateBlockAsync() {
            TetrisClient.Web.TetrisWebService.RotateBlockRequest inValue = new TetrisClient.Web.TetrisWebService.RotateBlockRequest();
            return ((TetrisClient.Web.TetrisWebService.TetrisWebServiceSoap)(this)).RotateBlockAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TetrisClient.Web.TetrisWebService.MoveBlockDownResponse TetrisClient.Web.TetrisWebService.TetrisWebServiceSoap.MoveBlockDown(TetrisClient.Web.TetrisWebService.MoveBlockDownRequest request) {
            return base.Channel.MoveBlockDown(request);
        }
        
        public string[][] MoveBlockDown() {
            TetrisClient.Web.TetrisWebService.MoveBlockDownRequest inValue = new TetrisClient.Web.TetrisWebService.MoveBlockDownRequest();
            TetrisClient.Web.TetrisWebService.MoveBlockDownResponse retVal = ((TetrisClient.Web.TetrisWebService.TetrisWebServiceSoap)(this)).MoveBlockDown(inValue);
            return retVal.MoveBlockDownResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TetrisClient.Web.TetrisWebService.MoveBlockDownResponse> TetrisClient.Web.TetrisWebService.TetrisWebServiceSoap.MoveBlockDownAsync(TetrisClient.Web.TetrisWebService.MoveBlockDownRequest request) {
            return base.Channel.MoveBlockDownAsync(request);
        }
        
        public System.Threading.Tasks.Task<TetrisClient.Web.TetrisWebService.MoveBlockDownResponse> MoveBlockDownAsync() {
            TetrisClient.Web.TetrisWebService.MoveBlockDownRequest inValue = new TetrisClient.Web.TetrisWebService.MoveBlockDownRequest();
            return ((TetrisClient.Web.TetrisWebService.TetrisWebServiceSoap)(this)).MoveBlockDownAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TetrisClient.Web.TetrisWebService.DropBlockResponse TetrisClient.Web.TetrisWebService.TetrisWebServiceSoap.DropBlock(TetrisClient.Web.TetrisWebService.DropBlockRequest request) {
            return base.Channel.DropBlock(request);
        }
        
        public string[][] DropBlock() {
            TetrisClient.Web.TetrisWebService.DropBlockRequest inValue = new TetrisClient.Web.TetrisWebService.DropBlockRequest();
            TetrisClient.Web.TetrisWebService.DropBlockResponse retVal = ((TetrisClient.Web.TetrisWebService.TetrisWebServiceSoap)(this)).DropBlock(inValue);
            return retVal.DropBlockResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TetrisClient.Web.TetrisWebService.DropBlockResponse> TetrisClient.Web.TetrisWebService.TetrisWebServiceSoap.DropBlockAsync(TetrisClient.Web.TetrisWebService.DropBlockRequest request) {
            return base.Channel.DropBlockAsync(request);
        }
        
        public System.Threading.Tasks.Task<TetrisClient.Web.TetrisWebService.DropBlockResponse> DropBlockAsync() {
            TetrisClient.Web.TetrisWebService.DropBlockRequest inValue = new TetrisClient.Web.TetrisWebService.DropBlockRequest();
            return ((TetrisClient.Web.TetrisWebService.TetrisWebServiceSoap)(this)).DropBlockAsync(inValue);
        }
        
        public int GetScore() {
            return base.Channel.GetScore();
        }
        
        public System.Threading.Tasks.Task<int> GetScoreAsync() {
            return base.Channel.GetScoreAsync();
        }
        
        public System.Data.DataTable GetHighScores() {
            return base.Channel.GetHighScores();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetHighScoresAsync() {
            return base.Channel.GetHighScoresAsync();
        }
        
        public void SubmitScore() {
            base.Channel.SubmitScore();
        }
        
        public System.Threading.Tasks.Task SubmitScoreAsync() {
            return base.Channel.SubmitScoreAsync();
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
    }
}
